/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pizzarendeles;

import javax.swing.JOptionPane;

/**
 *
 * @author CsorbaEszterKatinka(
 */
public class Pizzarendeles extends javax.swing.JFrame {

    /**
     * Creates new form Pizzarendeles
     */
    public Pizzarendeles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        pnlHatterpiros = new javax.swing.JPanel();
        pnlHattersarga = new javax.swing.JPanel();
        lblPepperoni = new javax.swing.JLabel();
        lblRendeles = new javax.swing.JLabel();
        lblKep = new javax.swing.JLabel();
        pnlAlap = new javax.swing.JPanel();
        lblMeret = new javax.swing.JLabel();
        lblTeszta = new javax.swing.JLabel();
        cbbTeszta = new javax.swing.JComboBox<>();
        lblSajt = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        rbtn24 = new javax.swing.JRadioButton();
        cbbSajt = new javax.swing.JComboBox<>();
        rbtn32 = new javax.swing.JRadioButton();
        rbtn45 = new javax.swing.JRadioButton();
        pnlFeltet = new javax.swing.JPanel();
        chbPepp = new javax.swing.JCheckBox();
        chbSonka = new javax.swing.JCheckBox();
        chbKuk = new javax.swing.JCheckBox();
        chbGomba = new javax.swing.JCheckBox();
        chbHagy = new javax.swing.JCheckBox();
        chbPar = new javax.swing.JCheckBox();
        chbAn = new javax.swing.JCheckBox();
        chbTofu = new javax.swing.JCheckBox();
        chbExtra = new javax.swing.JCheckBox();
        btnRendelem = new javax.swing.JButton();
        btnMegse = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        rbtnFizetesKp = new javax.swing.JRadioButton();
        rbtnFizetesKar = new javax.swing.JRadioButton();
        lblFizmod = new javax.swing.JLabel();
        lblDb = new javax.swing.JLabel();
        SprDarab = new javax.swing.JSpinner();
        lblktyosszeg = new javax.swing.JLabel();
        lblSzelet = new javax.swing.JLabel();
        lblElerhetoseg = new javax.swing.JLabel();
        lblKposszeg = new javax.swing.JLabel();
        txtfKpossz = new javax.swing.JTextField();
        txtfKtyossz = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pizzarendelés");
        setBackground(new java.awt.Color(255, 102, 102));

        pnlHatterpiros.setBackground(new java.awt.Color(178, 8, 8));

        pnlHattersarga.setBackground(new java.awt.Color(235, 207, 97));

        lblPepperoni.setBackground(new java.awt.Color(241, 224, 160));
        lblPepperoni.setFont(new java.awt.Font("Maiandra GD", 0, 36)); // NOI18N
        lblPepperoni.setText("Pepperoni Paradise");
        lblPepperoni.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)), new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 2, true)));
        lblPepperoni.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblRendeles.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 22)); // NOI18N
        lblRendeles.setText("Pizzarendelés:");

        lblKep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzarendeles/kepek/hosszukas.jpg"))); // NOI18N

        pnlAlap.setBackground(new java.awt.Color(241, 224, 160));
        pnlAlap.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)), "Pizza alap:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 0, 0))); // NOI18N

        lblMeret.setText("Méret:");

        lblTeszta.setText("Tészta:");

        cbbTeszta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Válasszon tésztát!", "Vékony tészta", "Vastag tészta", "Gluténmentes tészta" }));
        cbbTeszta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbbTeszta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTesztaActionPerformed(evt);
            }
        });

        lblSajt.setText("Sajt: ");

        jPanel4.setBackground(new java.awt.Color(241, 224, 160));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        buttonGroup2.add(rbtn24);
        rbtn24.setText("24cm");
        rbtn24.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtn24.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtn24ItemStateChanged(evt);
            }
        });
        rbtn24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn24ActionPerformed(evt);
            }
        });

        cbbSajt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normál", "Vegán" }));

        buttonGroup2.add(rbtn32);
        rbtn32.setText("32cm");
        rbtn32.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtn32ItemStateChanged(evt);
            }
        });
        rbtn32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn32ActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtn45);
        rbtn45.setText("45cm");
        rbtn45.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtn45ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlAlapLayout = new javax.swing.GroupLayout(pnlAlap);
        pnlAlap.setLayout(pnlAlapLayout);
        pnlAlapLayout.setHorizontalGroup(
            pnlAlapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlapLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAlapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAlapLayout.createSequentialGroup()
                        .addGroup(pnlAlapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTeszta)
                            .addComponent(lblSajt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlAlapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbSajt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbTeszta, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAlapLayout.createSequentialGroup()
                        .addComponent(lblMeret)
                        .addGap(28, 28, 28)
                        .addGroup(pnlAlapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtn32)
                            .addComponent(rbtn24)
                            .addComponent(rbtn45))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAlapLayout.setVerticalGroup(
            pnlAlapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlapLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(pnlAlapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMeret)
                    .addComponent(rbtn24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtn32)
                .addGap(3, 3, 3)
                .addComponent(rbtn45)
                .addGap(18, 18, 18)
                .addGroup(pnlAlapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlAlapLayout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addGroup(pnlAlapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTeszta)
                            .addComponent(cbbTeszta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlAlapLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSajt)
                            .addComponent(cbbSajt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnlFeltet.setBackground(new java.awt.Color(241, 224, 160));
        pnlFeltet.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)), "Feltétek:", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(153, 0, 0))); // NOI18N
        pnlFeltet.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        chbPepp.setText("Pepperoni");
        chbPepp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chbPepp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbTofuItemStateChanged(evt);
            }
        });
        chbPepp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbTofuStateChanged(evt);
            }
        });
        chbPepp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbTofuActionPerformed(evt);
            }
        });

        chbSonka.setText("Sonka");
        chbSonka.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chbSonka.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbTofuItemStateChanged(evt);
            }
        });
        chbSonka.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbTofuStateChanged(evt);
            }
        });
        chbSonka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbTofuActionPerformed(evt);
            }
        });

        chbKuk.setText("Kukorica");
        chbKuk.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chbKuk.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbTofuItemStateChanged(evt);
            }
        });
        chbKuk.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbTofuStateChanged(evt);
            }
        });
        chbKuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbTofuActionPerformed(evt);
            }
        });

        chbGomba.setText("Gomba");
        chbGomba.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chbGomba.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbTofuItemStateChanged(evt);
            }
        });
        chbGomba.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbTofuStateChanged(evt);
            }
        });
        chbGomba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbTofuActionPerformed(evt);
            }
        });

        chbHagy.setText("Hagyma");
        chbHagy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chbHagy.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbTofuItemStateChanged(evt);
            }
        });
        chbHagy.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbTofuStateChanged(evt);
            }
        });
        chbHagy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbHagyActionPerformed(evt);
            }
        });

        chbPar.setText("Paradicsom");
        chbPar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chbPar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbTofuItemStateChanged(evt);
            }
        });
        chbPar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbTofuStateChanged(evt);
            }
        });
        chbPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbParActionPerformed(evt);
            }
        });

        chbAn.setText("Ananász");
        chbAn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chbAn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbTofuItemStateChanged(evt);
            }
        });
        chbAn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbTofuStateChanged(evt);
            }
        });
        chbAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbTofuActionPerformed(evt);
            }
        });

        chbTofu.setText("Tofu");
        chbTofu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chbTofu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbTofuItemStateChanged(evt);
            }
        });
        chbTofu.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbTofuStateChanged(evt);
            }
        });
        chbTofu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbTofuActionPerformed(evt);
                chbTofActionerfordmed(evt);
            }
        });

        chbExtra.setText("+ extra sajt");
        chbExtra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        chbExtra.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chbTofuItemStateChanged(evt);
            }
        });
        chbExtra.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chbTofuStateChanged(evt);
            }
        });
        chbExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbExtraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlFeltetLayout = new javax.swing.GroupLayout(pnlFeltet);
        pnlFeltet.setLayout(pnlFeltetLayout);
        pnlFeltetLayout.setHorizontalGroup(
            pnlFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFeltetLayout.createSequentialGroup()
                .addGroup(pnlFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFeltetLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(pnlFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chbGomba, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbKuk, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbSonka, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbPepp, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbPar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbHagy, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbAn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbTofu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlFeltetLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(chbExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        pnlFeltetLayout.setVerticalGroup(
            pnlFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFeltetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbPepp)
                    .addComponent(chbHagy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbSonka)
                    .addComponent(chbPar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbAn)
                    .addComponent(chbKuk))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlFeltetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chbGomba)
                    .addComponent(chbTofu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chbExtra)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRendelem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRendelem.setText("Megrendelem");
        btnRendelem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        btnRendelem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRendelem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRendelemMouseClicked(evt);
            }
        });
        btnRendelem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRendelemActionPerformed(evt);
            }
        });

        btnMegse.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMegse.setText("  Mégse  ");
        btnMegse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        btnMegse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMegse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegseActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(241, 224, 160));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, null, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));

        buttonGroup3.add(rbtnFizetesKp);
        rbtnFizetesKp.setText("Készpéz átvételkor");
        rbtnFizetesKp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtnFizetesKp.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnFizetesKpItemStateChanged(evt);
            }
        });
        rbtnFizetesKp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbtnFizetesKpStateChanged(evt);
            }
        });
        rbtnFizetesKp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnFizetesKpMouseClicked(evt);
            }
        });
        rbtnFizetesKp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFizetesKpActionPerformed(evt);
            }
        });

        buttonGroup3.add(rbtnFizetesKar);
        rbtnFizetesKar.setText("Kártyás utalás");
        rbtnFizetesKar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtnFizetesKar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtnFizetesKarItemStateChanged(evt);
            }
        });
        rbtnFizetesKar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnFizetesKarMouseClicked(evt);
            }
        });

        lblFizmod.setText("Válasszon fizetési módot:");

        lblDb.setText("Darabszám (max.10):");

        SprDarab.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        SprDarab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnFizetesKp)
                            .addComponent(rbtnFizetesKar)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFizmod)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblDb)
                                .addGap(18, 18, 18)
                                .addComponent(SprDarab, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDb)
                    .addComponent(SprDarab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(lblFizmod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnFizetesKp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnFizetesKar)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        lblktyosszeg.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblktyosszeg.setText("Kártyás összeg:");

        lblSzelet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pizzarendeles/kepek/kispizzaszines2.png"))); // NOI18N

        lblElerhetoseg.setText("<html><a href=\"facebook.com\">Elérhetőségünk</a></html>");
        lblElerhetoseg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblKposszeg.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblKposszeg.setText("Készpénzes összeg: ");

        txtfKpossz.setText("xxx");

        txtfKtyossz.setText("2500ft");

        javax.swing.GroupLayout pnlHattersargaLayout = new javax.swing.GroupLayout(pnlHattersarga);
        pnlHattersarga.setLayout(pnlHattersargaLayout);
        pnlHattersargaLayout.setHorizontalGroup(
            pnlHattersargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHattersargaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHattersargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHattersargaLayout.createSequentialGroup()
                        .addComponent(lblRendeles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(412, 412, 412))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHattersargaLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(pnlHattersargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHattersargaLayout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addGroup(pnlHattersargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlHattersargaLayout.createSequentialGroup()
                                        .addComponent(lblKposszeg)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(pnlHattersargaLayout.createSequentialGroup()
                                        .addGroup(pnlHattersargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblktyosszeg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(pnlHattersargaLayout.createSequentialGroup()
                                                .addGroup(pnlHattersargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtfKpossz, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtfKtyossz, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(lblSzelet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(202, 202, 202))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHattersargaLayout.createSequentialGroup()
                                .addGroup(pnlHattersargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlHattersargaLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(lblElerhetoseg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnRendelem, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnMegse, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlHattersargaLayout.createSequentialGroup()
                                        .addComponent(pnlAlap, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(pnlFeltet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(172, 172, 172))))
                    .addGroup(pnlHattersargaLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(lblPepperoni)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblKep, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );
        pnlHattersargaLayout.setVerticalGroup(
            pnlHattersargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHattersargaLayout.createSequentialGroup()
                .addComponent(lblKep, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblPepperoni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblRendeles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlHattersargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlFeltet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAlap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pnlHattersargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHattersargaLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblElerhetoseg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHattersargaLayout.createSequentialGroup()
                        .addGroup(pnlHattersargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHattersargaLayout.createSequentialGroup()
                                .addComponent(lblKposszeg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfKpossz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblktyosszeg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtfKtyossz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlHattersargaLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lblSzelet)))
                        .addGap(47, 47, 47)
                        .addGroup(pnlHattersargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRendelem)
                            .addComponent(btnMegse))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        lblPepperoni.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout pnlHatterpirosLayout = new javax.swing.GroupLayout(pnlHatterpiros);
        pnlHatterpiros.setLayout(pnlHatterpirosLayout);
        pnlHatterpirosLayout.setHorizontalGroup(
            pnlHatterpirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHatterpirosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(pnlHattersarga, javax.swing.GroupLayout.PREFERRED_SIZE, 564, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        pnlHatterpirosLayout.setVerticalGroup(
            pnlHatterpirosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHatterpirosLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(pnlHattersarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHatterpiros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlHatterpiros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rbtn24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn24ActionPerformed
        
    }//GEN-LAST:event_rbtn24ActionPerformed

    private void chbHagyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbHagyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbHagyActionPerformed

    private void chbParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbParActionPerformed
        
    }//GEN-LAST:event_chbParActionPerformed

    private void chbExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbExtraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbExtraActionPerformed

    private void rbtnFizetesKpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFizetesKpActionPerformed
        
        
    }//GEN-LAST:event_rbtnFizetesKpActionPerformed

    private void cbbTesztaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTesztaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbTesztaActionPerformed

    private void btnRendelemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRendelemActionPerformed
        JOptionPane.showMessageDialog(rootPane, "tesztverzió", "FIGYELMEZTETÉS", 2);
    }//GEN-LAST:event_btnRendelemActionPerformed

    private void btnMegseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnMegseActionPerformed

    private void btnRendelemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRendelemMouseClicked
        int     ikonTipus = JOptionPane.INFORMATION_MESSAGE; //
    JOptionPane.showMessageDialog(rootPane, "Az Ön rendelését felvettük.", "RENDELÉSÉT FELVETTÜK", 1);
    }//GEN-LAST:event_btnRendelemMouseClicked

    private void rbtnFizetesKpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbtnFizetesKpStateChanged
        
       
    }//GEN-LAST:event_rbtnFizetesKpStateChanged



    private void rbtnFizetesKarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnFizetesKarMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Az Ön kárytával való fizetése érdekében átirányítjuk a bankártya oldalunka.", "KÁRTYÁVAL", 1);
    }//GEN-LAST:event_rbtnFizetesKarMouseClicked

    private void rbtnFizetesKpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnFizetesKpMouseClicked
        JOptionPane.showMessageDialog(rootPane, "Kérem, hogy mikor megérkezik futárunk álljon készen a fizetendő összeggel.", "KÉSZPÉNZZEL", 1);
    }//GEN-LAST:event_rbtnFizetesKpMouseClicked

    private void chbTofuStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chbTofuStateChanged
        
    }//GEN-LAST:event_chbTofuStateChanged

    private void rbtnFizetesKpItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnFizetesKpItemStateChanged
        csere();
        
    }//GEN-LAST:event_rbtnFizetesKpItemStateChanged

    private void chbTofuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chbTofuItemStateChanged
        
    }//GEN-LAST:event_chbTofuItemStateChanged

    private void chbTofuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbTofuActionPerformed
        
    }//GEN-LAST:event_chbTofuActionPerformed

    private void chbTofActionerfordmed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbTofActionerfordmed
        
    }//GEN-LAST:event_chbTofActionerfordmed

    private void rbtn24ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtn24ItemStateChanged
        if (rbtn24.isSelected() || rbtn32.isSelected() || rbtn45.isSelected()){
            chbPepp.setEnabled(true);
            chbSonka.setEnabled(true);
            chbKuk.setEnabled(true);
            chbGomba.setEnabled(true);
            chbHagy.setEnabled(true);
            chbPar.setEnabled(true);
            chbAn.setEnabled(true);
            chbTofu.setEnabled(true);
            chbExtra.setEnabled(true);
        }else{
            chbPepp.setEnabled(false);
            chbSonka.setEnabled(false);
            chbKuk.setEnabled(false);
            chbGomba.setEnabled(false);
            chbHagy.setEnabled(false);
            chbPar.setEnabled(false);
            chbAn.setEnabled(false);
            chbTofu.setEnabled(false);
            chbExtra.setEnabled(false);
        }
    }//GEN-LAST:event_rbtn24ItemStateChanged

    private void rbtnFizetesKarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtnFizetesKarItemStateChanged
        
        
    }//GEN-LAST:event_rbtnFizetesKarItemStateChanged

    private void rbtn32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtn32ActionPerformed

    private void rbtn32ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtn32ItemStateChanged
        if (rbtn24.isSelected() || rbtn32.isSelected() || rbtn45.isSelected()){
            chbPepp.setEnabled(true);
            chbSonka.setEnabled(true);
            chbKuk.setEnabled(true);
            chbGomba.setEnabled(true);
            chbHagy.setEnabled(true);
            chbPar.setEnabled(true);
            chbAn.setEnabled(true);
            chbTofu.setEnabled(true);
            chbExtra.setEnabled(true);
        }else{
            chbPepp.setEnabled(false);
            chbSonka.setEnabled(false);
            chbKuk.setEnabled(false);
            chbGomba.setEnabled(false);
            chbHagy.setEnabled(false);
            chbPar.setEnabled(false);
            chbAn.setEnabled(false);
            chbTofu.setEnabled(false);
            chbExtra.setEnabled(false);
        }
    }//GEN-LAST:event_rbtn32ItemStateChanged

    private void rbtn45ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtn45ItemStateChanged
        if (rbtn24.isSelected() || rbtn32.isSelected() || rbtn45.isSelected()){
            chbPepp.setEnabled(true);
            chbSonka.setEnabled(true);
            chbKuk.setEnabled(true);
            chbGomba.setEnabled(true);
            chbHagy.setEnabled(true);
            chbPar.setEnabled(true);
            chbAn.setEnabled(true);
            chbTofu.setEnabled(true);
            chbExtra.setEnabled(true);
        }else{
            chbPepp.setEnabled(false);
            chbSonka.setEnabled(false);
            chbKuk.setEnabled(false);
            chbGomba.setEnabled(false);
            chbHagy.setEnabled(false);
            chbPar.setEnabled(false);
            chbAn.setEnabled(false);
            chbTofu.setEnabled(false);
            chbExtra.setEnabled(false);
        }
    }//GEN-LAST:event_rbtn45ItemStateChanged

    private void csere() {
        csere();
        String s = txtfKpossz.getText();
        txtfKpossz.setText(txtfKtyossz.getText());
        txtfKtyossz.setText(s);
    }

  
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pizzarendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pizzarendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pizzarendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pizzarendeles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pizzarendeles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner SprDarab;
    private javax.swing.JButton btnMegse;
    private javax.swing.JButton btnRendelem;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cbbSajt;
    private javax.swing.JComboBox<String> cbbTeszta;
    private javax.swing.JCheckBox chbAn;
    private javax.swing.JCheckBox chbExtra;
    private javax.swing.JCheckBox chbGomba;
    private javax.swing.JCheckBox chbHagy;
    private javax.swing.JCheckBox chbKuk;
    private javax.swing.JCheckBox chbPar;
    private javax.swing.JCheckBox chbPepp;
    private javax.swing.JCheckBox chbSonka;
    private javax.swing.JCheckBox chbTofu;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblDb;
    private javax.swing.JLabel lblElerhetoseg;
    private javax.swing.JLabel lblFizmod;
    private javax.swing.JLabel lblKep;
    private javax.swing.JLabel lblKposszeg;
    private javax.swing.JLabel lblMeret;
    private javax.swing.JLabel lblPepperoni;
    private javax.swing.JLabel lblRendeles;
    private javax.swing.JLabel lblSajt;
    private javax.swing.JLabel lblSzelet;
    private javax.swing.JLabel lblTeszta;
    private javax.swing.JLabel lblktyosszeg;
    private javax.swing.JPanel pnlAlap;
    private javax.swing.JPanel pnlFeltet;
    private javax.swing.JPanel pnlHatterpiros;
    private javax.swing.JPanel pnlHattersarga;
    private javax.swing.JRadioButton rbtn24;
    private javax.swing.JRadioButton rbtn32;
    private javax.swing.JRadioButton rbtn45;
    private javax.swing.JRadioButton rbtnFizetesKar;
    private javax.swing.JRadioButton rbtnFizetesKp;
    private javax.swing.JTextField txtfKpossz;
    private javax.swing.JTextField txtfKtyossz;
    // End of variables declaration//GEN-END:variables

    
}
